import { Routes } from '@angular/router';
import { AboutComponent } from './features/about/about.component';
import { LoginComponent } from './features/account/login/login.component';
import { RegisterComponent } from './features/account/register/register.component';
import { HomeComponent } from './features/home/home.component';
import { OrderConfirmationComponent } from './features/orders/order-confirmation/order-confirmation.component';
import { OrderTrackingComponent } from './features/orders/order-tracking/order-tracking.component';
import { ProductDetailsComponent } from './features/product-details/product-details.component';
import { CartViewComponent } from './features/product-order/cart-view/cart-view.component';
import { CheckoutComponent } from './features/product-order/checkout/checkout.component';
import { ChickenComponent } from './features/products/chicken/chicken.component';
import { EggsComponent } from './features/products/eggs/eggs.component';
import { ProductListingComponent } from './features/products/product-listing/product-listing.component';
import { SplashComponent } from './features/splash/splash.component';
import { ProductDetailsComponentEggs } from './features/product-details-eggs/product-details-eggs.component';
import { OrderCancellationComponent } from './shared/order-cancellation/order-cancellation.component';
import { FaqComponent } from './shared/faq/faq.component';
import { PrivacyPolicyComponent } from './shared/privacy-policy/privacy-policy.component';
import { TermsAndConditionsComponent } from './shared/terms-and-conditions/terms-and-conditions.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'home', redirectTo: '', pathMatch: 'full' },
  { path: 'splash', component: SplashComponent },
  { path: 'about', component: AboutComponent },
  { path: 'login', component: LoginComponent },
  { path: 'register', component: RegisterComponent },
  { path: 'products', component: ProductListingComponent },
  { path: 'products/chicken', component: ChickenComponent },
  { path: 'products/product-details', component: ProductDetailsComponent },
  { path: 'products/product-details-eggs', component: ProductDetailsComponentEggs },
  { path: 'products/eggs', component: EggsComponent },
  { path: 'products/:category', component: ProductListingComponent },
  { path: 'terms', component: TermsAndConditionsComponent },
  { path: 'faq', component: FaqComponent },
  { path: 'privacy-policy', component: PrivacyPolicyComponent },
  { path: 'order-cancellation', component: OrderCancellationComponent },
  { path: 'cart', component: CartViewComponent },
  { path: 'checkout', component: CheckoutComponent },
  { path: 'order-confirmation', component: OrderConfirmationComponent },
  { path: 'order-tracking', component: OrderTrackingComponent },
  { path: '**', redirectTo: '' },
];
